minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
---
title: Satwik Kansal's blog
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
locale: en
title_separator: "-"
name: Satwik Kansal
description: 'Freelance Software Developer and Open Source enthusiast experienced
  in Data Science and Web Development.

'
url: http://blog.satwikkansal.xyz
baseurl: 
repository: satwikkansal/satwikkansal.github.io
teaser: 
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: satwik
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields:
  - name
  - email
  - url
  - message
  branch: gh-pages
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: false
  path: _data/comments/{options.slug}
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path: 
google_site_verification: IoC_F49PVEB-g10hvzr5RTmjxW1LIYldwrNcAKrFiPA
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username: satwikkansal
facebook:
  username: satwikkansal
  app_id: '296348977464170'
  publisher: 
og_image: 
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to  social media profiles
    - "https://www.linkedin.com/in/satwikkansal"
    - "https://www.facebook.com/satwikkansal"
    - "https://plus.google.com/u/0/100516829514193489870"

# Analytics
analytics:
  provider: google
  google:
    tracking_id: UA-69269552-4
author:
  name: Satwik Kansal
  avatar: https://www.gravatar.com/avatar/763a2074e6b54615855a13656f2cb717
  bio: 'A Freelance Software Developer actively involved in Open Source,  experienced
    in Data Science and Web Development.

'
  location: New Delhi, India
  email: satwikkansal@gmail.com
  uri: http://satwikkansal.xyz
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: https://www.facebook.com/satwikkansal
  foursquare: 
  github: satwikkansal
  google_plus: 
  keybase: 
  instagram: 
  lastfm: 
  linkedin: https://www.linkedin.com/in/satwikkansal
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: satwikkansal
  vine: 
  weibo: 
  xing: 
  youtube: 
  quora: Satwik-Kansal-1
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- "/docs"
- "/test"
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md,mdown
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
sass:
  sass_dir: _sass
  style: compressed
permalink: "/posts/:categories/:title/"
paginate: 4
paginate_path: "/page:num/"
gems:
- jekyll-paginate
- jekyll-archives
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
tag_archive:
  type: liquid
  path: "/tags/"
category_archive:
  type: liquid
  path: "/categories/"
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
related: true
